version: '3'

services:
  site1sub:
    image: nginx:alpine
    volumes:
      - .:/usr/share/nginx/html/
    labels:
      - traefik.backend=site1sub
      - "traefik.frontend.rule=Host:site1.org;PathPrefixStrip: /sub/"
    networks: 
      - proxy

networks:
  proxy:
    external:
      name: proxy