version: '3'

services:
  site1sub:
    image: nginx:alpine
    volumes:
      - .:/usr/share/nginx/html/
    deploy:
      labels:
        - "traefik.http.routers.site1sub.rule=Host(`site1.org`) && PathPrefix(`/sub`)"
        - "traefik.http.middlewares.site1sub.stripprefix.prefixes=/sub"
        - "traefik.http.routers.site1sub.middlewares=site1sub@docker"
        - traefik.http.services.site1sub.loadbalancer.server.port=80
    networks: 
      - proxy

networks:
  proxy:
    external:
      name: proxy