version: '3'

services:
  site1:
    image: nginx:alpine
    volumes:
      - .:/usr/share/nginx/html/
    deploy:
      labels:
        - "traefik.http.routers.site1.rule=Host(`site1.org`)"
        - traefik.http.services.site1.loadbalancer.server.port=80
    networks: 
      - proxy

networks:
  proxy:
    external:
      name: proxy