version: '3'

services:
  site2:
    image: nginx:alpine
    volumes:
      - .:/usr/share/nginx/html/
    deploy:
      labels:
        - traefik.enable=true
        - "traefik.http.routers.site2.rule=Host(`site2.org`)"
        - traefik.http.services.site2.loadbalancer.server.port=80
      replicas: 2
    networks: 
      - proxy

networks:
  proxy:
    external:
      name: proxy