version: '3'

services:
  app:
    image: dockersamples/visualizer:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.backend=viz
      - traefik.frontend.rule=Host:viz.org
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - proxy

networks:
  proxy:
    external:
      name: proxy