version: '3'

services:
  app:
    image: dockersamples/visualizer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.http.routers.viz.rule=Host(`viz.org`)"
        - traefik.http.services.viz.loadbalancer.server.port=8080
    networks: 
      - proxy

networks:
  proxy:
    external:
      name: proxy