version: '3'

services:
  app:
    image: dockersamples/visualizer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - "traefik.http.routers.viz.rule=Host(`viz.org`) || (Host(`viz.org`) && PathPrefix(`/apis`))"
        - traefik.http.services.viz.loadbalancer.server.port=8080
        - traefik.http.services.viz.loadbalancer.passhostheader=true
    networks: 
      - proxy

networks:
  proxy:
    external:
      name: proxy